'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace BatchEditDateRanges


    Partial Public Class [Default]

        ''' <summary>
        ''' form1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        ''' <summary>
        ''' PageContainer control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected PageContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        ''' <summary>
        ''' DateRangeFormLayout control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected DateRangeFormLayout As Global.DevExpress.Web.ASPxFormLayout

        ''' <summary>
        ''' StartDate control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected StartDate As Global.DevExpress.Web.ASPxDateEdit

        ''' <summary>
        ''' EndDate control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected EndDate As Global.DevExpress.Web.ASPxDateEdit

        ''' <summary>
        ''' SubmitHyperLink control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SubmitHyperLink As Global.DevExpress.Web.ASPxHyperLink

        ''' <summary>
        ''' SubmitButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SubmitButton As Global.DevExpress.Web.ASPxButton
    End Class
End Namespace
